// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function CancelCurrentOperation():Promise<void>;

export function CheckLocalFiles():Promise<Array<model.LocalArchive>>;

export function DeleteLocalGachaHistory(arg1:string):Promise<void>;

export function ExportData(arg1:string,arg2:string):Promise<string>;

export function ExportDataDirect(arg1:string,arg2:string):Promise<string>;

export function GetPoolConfig():Promise<model.PoolConfigList>;

export function ImportTemporaryJson():Promise<main.ImportResponse>;

export function LoadLocalGachaHistory(arg1:string,arg2:string):Promise<main.LocalDataResponse>;

export function LoginAndFetchPlayers(arg1:string):Promise<main.LoginResponse>;

export function OpenDataFolder():Promise<void>;

export function OpenOfficialLoginWindow():Promise<main.LoginResponse>;

export function ReloadFrontend():Promise<void>;

export function SyncDataByChoice(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function UpdatePoolConfig():Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMinSize():Promise<void>;

export function WindowToggleMaxSize():Promise<boolean>;
