// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCurrentOperation() {
  return window['go']['main']['App']['CancelCurrentOperation']();
}

export function CheckLocalFiles() {
  return window['go']['main']['App']['CheckLocalFiles']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteLocalGachaHistory(arg1) {
  return window['go']['main']['App']['DeleteLocalGachaHistory'](arg1);
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function ExportDataDirect(arg1, arg2) {
  return window['go']['main']['App']['ExportDataDirect'](arg1, arg2);
}

export function GetPoolConfig() {
  return window['go']['main']['App']['GetPoolConfig']();
}

export function ImportTemporaryJson() {
  return window['go']['main']['App']['ImportTemporaryJson']();
}

export function LoadLocalGachaHistory(arg1, arg2) {
  return window['go']['main']['App']['LoadLocalGachaHistory'](arg1, arg2);
}

export function LoginAndFetchPlayers(arg1) {
  return window['go']['main']['App']['LoginAndFetchPlayers'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function OpenOfficialLoginWindow() {
  return window['go']['main']['App']['OpenOfficialLoginWindow']();
}

export function ReloadFrontend() {
  return window['go']['main']['App']['ReloadFrontend']();
}

export function SyncDataByChoice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncDataByChoice'](arg1, arg2, arg3, arg4);
}

export function UpdatePoolConfig() {
  return window['go']['main']['App']['UpdatePoolConfig']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinSize() {
  return window['go']['main']['App']['WindowMinSize']();
}

export function WindowToggleMaxSize() {
  return window['go']['main']['App']['WindowToggleMaxSize']();
}
